Directory.Build.props
Document/Document.csproj
Excel/Excel.csproj
Excel/Worksheet.cs
Global/Charts/BarChart .cs
Global/Charts/BarFamilyChart.cs
Global/Charts/ChartBase.cs
Global/Charts/ChartColor.cs
Global/Charts/ChartStyle.cs
Global/Charts/ColumnChart.cs
Global/Global.csproj
Global/GlobalConstants.cs
Global/Utils/ConverterUtils.cs
Global/models/ChartBaseModel.cs
Presentation/Internal/components/Chart.cs
Presentation/Internal/utils/Reformatting.cs
Presentation/Presentation.csproj
Tests/Presentation.cs
Tests/Tests.csproj

Added support to insert bar and column chart replacing exisitng shape

3 bar chart

---

Directory.Build.props
Global/Charts/AreaChart.cs
Global/Charts/AreaFamilyChart.cs
Global/Charts/BarChart .cs
Global/Charts/BarFamilyChart.cs
Global/Charts/ChartBase.cs
Global/Charts/ChartColor.cs
Global/Charts/ColumnChart.cs
Global/Charts/ColumnFamilyChart.cs
Global/Charts/LineChart.cs
Global/Charts/LineFamilyChart.cs
Global/Charts/PieChart.cs
Global/Charts/PieFamilyChart.cs
Global/GlobalConstants.cs
Global/Utils/ConverterUtils.cs
Global/models/AreaChartModel.cs
Global/models/BarChartModel.cs
Global/models/ChartBaseModel.cs
Global/models/ColumnChartModel.cs
Global/models/LineChartModel.cs
Global/models/PieChartModel.cs
Presentation/Internal/Parts/Slide.cs
Presentation/Internal/PresentationCore.cs
Presentation/Internal/components/Chart.cs
Tests/Presentation.cs

- Series Data Label Update
- Series Color Options Update
- Code Refactoring

3 grid line options

---

Directory.Build.props
Global/Charts/AreaFamilyChart.cs
Global/Charts/BarFamilyChart.cs
Global/Charts/ChartBase.cs
Global/Charts/ColumnFamilyChart.cs
Global/Charts/LineFamilyChart.cs
Global/Charts/PieFamilyChart.cs
Global/GlobalConstants.cs
Global/Utils/ConverterUtils.cs
Global/models/AreaChartModel.cs
Global/models/BarChartModel.cs
Global/models/ChartBaseModel.cs
Global/models/ColumnChartModel.cs
Global/models/LineChartModel.cs
Global/models/PieChartModel.cs
Presentation/Internal/Parts/Slide.cs
Presentation/Internal/components/Chart.cs
Presentation/Internal/components/Table.cs
Presentation/Models/TableModel.cs
README.md
Tests/Presentation.cs

3 chart excel formatting

---

Directory.Build.props
Global/Charts/AreaChart.cs
Global/Charts/AreaFamilyChart.cs
Global/Charts/BarChart .cs
Global/Charts/BarFamilyChart.cs
Global/Charts/ChartBase.cs
Global/Charts/ColumnChart.cs
Global/Charts/ColumnFamilyChart.cs
Global/Charts/LineChart.cs
Global/Charts/LineFamilyChart.cs
Global/Charts/PieChart.cs
Global/Charts/PieFamilyChart.cs
Global/Charts/ScatterChart.cs
Global/Charts/ScatterFamilyChart.cs
Global/Models/AreaChartModel.cs
Global/Models/BarChartModel.cs
Global/Models/ChartBaseModel.cs
Global/Models/ColumnChartModel.cs
Global/Models/LineChartModel.cs
Global/Models/ScatterChartModel.cs
Presentation/Internal/Components/Chart.cs
Presentation/Internal/Parts/Slide.cs
Tests/Presentation.cs

- Added Support For Scatter Chart Types Except Bubble chart
- Chart Axis Bugs addressed

20 ppt scatter chart support

---

Directory.Build.props
Global/Charts/ChartBase.cs
Global/Charts/ScatterFamilyChart.cs
Global/Models/ChartBaseModel.cs
Tests/Presentation.cs

- Chart Data Insert Optimisation and Bug Fixes
- Bubble Chart Support

22 ppt bubble chart support 4

---

Directory.Build.props
Global/Charts/AreaFamilyChart.cs
Global/Charts/BarFamilyChart.cs
Global/Charts/ChartBase.cs
Global/Charts/ColumnFamilyChart.cs
Global/Charts/LineFamilyChart.cs
Global/Charts/PieFamilyChart.cs
Global/Charts/ScatterFamilyChart.cs
Global/Models/AreaChartModel.cs
Global/Models/BarChartModel.cs
Global/Models/ChartBaseModel.cs
Global/Models/ColumnChartModel.cs
Global/Models/LineChartModel.cs
Global/Models/PieChartModel.cs
Global/Models/ScatterChartModel.cs
Presentation/Internal/Components/Table.cs
Presentation/Models/TableModel.cs
Tests/Presentation.cs

- Data Label Exception Handling Update
- Data Label Options Update

27 data label

---

Directory.Build.props
Excel/ShareString.cs
Excel/Spreadsheet.cs
Excel/Worksheet.cs
Global/Global.csproj

- Share string update for performance improvement

Share String support Update

---

Directory.Build.props
Excel/Models/SpreadsheetModel.cs
Excel/Models/StylesModel.cs
Excel/Models/WorksheetModel.cs
Excel/ShareString.cs
Excel/Spreadsheet.cs
Excel/SpreadsheetCore.cs
Excel/Styles.cs
Global/Charts/AreaFamilyChart.cs
Global/Charts/BarFamilyChart.cs
Global/Charts/ChartBase.cs
Global/Charts/ColumnFamilyChart.cs
Global/Charts/LineFamilyChart.cs
Global/Charts/PieFamilyChart.cs
Global/Charts/ScatterFamilyChart.cs
Global/Models/ChartBaseModel.cs
Global/Models/ChartDataModel.cs
Global/Models/ColumnChartModel.cs
Global/Models/ThemeModel.cs
Global/Parts/Theme.cs
Presentation/Internal/Components/Chart.cs
Presentation/Internal/Components/Picture.cs
Presentation/Internal/Components/Shape.cs
Presentation/Internal/Components/TextBox.cs
Presentation/Internal/Parts/Slide.cs
Presentation/Models/PowerPointModel.cs
Tests/Excel.cs
Tests/Presentation.cs

- Excel Default Stye Sheet
- Excel Default Theme
- Chart Number Formating

29 excel style update

---

Directory.Build.props
Excel/Models/SpreadsheetModel.cs
Excel/Models/StylesModel.cs
Excel/Models/WorksheetModel.cs
Excel/ShareString.cs
Excel/Spreadsheet.cs
Excel/SpreadsheetCore.cs
Excel/Styles.cs
Excel/Worksheet.cs
Presentation/Internal/Components/Chart.cs
Presentation/Public/PowerPoint.cs
Tests/Excel.cs
Tests/Presentation.cs

28 excel formatting

---

Directory.Build.props
Global/Components/CommonProperties.cs
Tests/Presentation.cs

- Fixes #(issue number)
- Added Text alignment centre option for text box
Please describe:
- Changes to existing Global/Components/CommonProperties.cs -> GetTextAlignmentValue functionality.
Please provide details on how these changes have been tested to ensure they work as intended and do not break existing features:
Before submitting your PR, please review and confirm the following:

chore: Added Text Center

---

.github/workflows/nuget-publish.yml
.github/workflows/pr-validation-main.yml
Directory.Build.props
Tests/Presentation.cs
Tests/Tests.csproj

pipeline update

---

Global/Components/Charts/2007/PieChart.cs
Global/Models/2007/ChartBaseModel.cs

- [ x] Bugfix (Issue)
- Fixes #(issue number)
- Briefly describe the issue and your approach to resolving it.
- Explain the rationale behind the new feature.
- Describe the functionality being added.
Please describe:
- Changes to existing files/functionality.
- New files or functionalities added (if applicable).
Please provide details on how these changes have been tested to ensure they work as intended and do not break existing features:
Before submitting your PR, please review and confirm the following:
Include any additional information or context that would assist the reviewers in understanding your changes.

feat: Added a Data label number format for chart labels

---

Global/Components/Charts/2007/ChartBase.cs
Global/Components/Charts/2007/LineChart.cs
Global/Components/Charts/2013/ChartAdvanced.cs
Global/Models/2007/ChartBaseModel.cs
Global/Models/2007/LineChartModel.cs
Global/Utils/Validation.cs
Presentation/Components/2007/Table.cs
Tests/Presentation.cs

- feat: Pie Chart Data Labels Formatting
- feat: Dynamic X,Y,Z Axis Line Color for Charts
- feat: Added Smooth Line option for line chart
- feat: Table Cell Border Color ( Needs Review)
- Fixes #(issue number)
- Briefly describe the issue and your approach to resolving it.
- Explain the rationale behind the new feature.
- Describe the functionality being added.
Please describe:
- Changes to existing files/functionality.
- New files or functionalities added (if applicable).
Please provide details on how these changes have been tested to ensure they work as intended and do not break existing features:
Before submitting your PR, please review and confirm the following:
Include any additional information or context that would assist the …

Feature - Line Chart, Pie Chart, Axis Line, Table Border

---

Directory.Build.props
Global/Components/2007/CommonProperties.cs
Global/Models/2007/CommonPropertiesModel.cs
Global/Models/2007/TextBoxModel.cs
Presentation/Components/2007/TextBox.cs
Tests/Presentation.cs

Adding Bullets and numbering option

Bullets and numbering

---

Directory.Build.props
Global/Global.csproj
Global/Models/2007/PrivacyProperties.cs
Presentation/Public/PowerPoint.cs
Spreadsheet/Components/2007/TextBox.cs
Spreadsheet/Public/Excel.cs
Tests/Presentation.cs
Tests/Spreadsheet.cs

Adding anonymous data collection

---

Directory.Build.props
Global/Global.csproj

open xml core library update

---

Directory.Build.props
Global/Global.csproj
Global/Models/2007/PrivacyProperties.cs
Tests/Presentation.cs
Tests/Spreadsheet.cs

rollback openXML-SDK v3.0.2
the latest version is breaking excel charts.

Privacy details and setup update

---

Directory.Build.props
Presentation/Components/2007/Shape.cs

- Updated Get shape property to get shape current dimension and position

Get Shape Property Update

---

Directory.Build.props

Release Version update

---

.github/workflows/nuget-publish.yml
Directory.Build.props
Spreadsheet/Internal/SpreadsheetCore.cs
Spreadsheet/Parts/Styles.cs

- Default Style, Share String & Calculation Chain parts bug fix.
- New file default content fix

Auto tag code version using actions

---

.github/workflows/nuget-publish.yml

publish pipeline fix

---

Directory.Build.props
Spreadsheet/Components/2007/Worksheet.cs
Spreadsheet/Internal/Spreadsheet.cs
Spreadsheet/Internal/SpreadsheetCore.cs
Spreadsheet/Public/Excel.cs
Tests/Spreadsheet.cs

- Set selected/active cell in a sheet
- Set active sheet to be selected on file open
- Worksheet defaults for new file
- Calculation chain initialize fix

Excel view

---

Directory.Build.props
Spreadsheet/Components/2007/Worksheet.cs
Spreadsheet/Internal/Spreadsheet.cs
Spreadsheet/Models/2007/WorksheetModel.cs
Tests/Spreadsheet.cs

- Added sheet view option update

More view options

---

Directory.Build.props
Spreadsheet/Components/2007/Worksheet.cs
Spreadsheet/Models/2007/WorksheetModel.cs
Tests/Spreadsheet.cs

Test Coverage update
